<?php

namespace Aoceu\VerbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TenseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenseTypeRepository extends EntityRepository
{
}
