parameters:
#    aoceu_tools.example.class: Aoceu\ToolsBundle\Example

services:
#    aoceu_tools.example:
#        class: %aoceu_tools.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
