<?php

namespace Aoceu\VerbBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TenseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Aoceu\VerbBundle\Controller\TenseController();
        return $instance;
    }
}
