parameters:
#    aoceu_verb.example.class: Aoceu\VerbBundle\Example

services:
#    aoceu_verb.example:
#        class: %aoceu_verb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
